[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.build-type = "Debug"

[project]
name = "OXRPresentationPython"
version = "0.0.1"

dependencies = [
    "torch >= 2.2",
]